/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ChainOfCustody {
  export type CustodyRecordStruct = {
    from: AddressLike;
    to: AddressLike;
    locationGPS: string;
    timestamp: BigNumberish;
    notes: string;
  };

  export type CustodyRecordStructOutput = [
    from: string,
    to: string,
    locationGPS: string,
    timestamp: bigint,
    notes: string
  ] & {
    from: string;
    to: string;
    locationGPS: string;
    timestamp: bigint;
    notes: string;
  };
}

export interface ChainOfCustodyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "currentOwner"
      | "custodyChain"
      | "getCurrentOwner"
      | "getCustodyHistory"
      | "identityRegistry"
      | "initializeCustody"
      | "initiateTransfer"
      | "pendingTransfer"
      | "productRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CustodyTransferred" | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "currentOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "custodyChain",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCustodyHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeCustody",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "productRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "custodyChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCustodyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeCustody",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productRegistry",
    data: BytesLike
  ): Result;
}

export namespace CustodyTransferredEvent {
  export type InputTuple = [
    productId: BytesLike,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [productId: string, from: string, to: string];
  export interface OutputObject {
    productId: string;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    productId: BytesLike,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [productId: string, from: string, to: string];
  export interface OutputObject {
    productId: string;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainOfCustody extends BaseContract {
  connect(runner?: ContractRunner | null): ChainOfCustody;
  waitForDeployment(): Promise<this>;

  interface: ChainOfCustodyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<
    [_productId: BytesLike, _locationGPS: string, _notes: string],
    [void],
    "nonpayable"
  >;

  currentOwner: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  custodyChain: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, string] & {
        from: string;
        to: string;
        locationGPS: string;
        timestamp: bigint;
        notes: string;
      }
    ],
    "view"
  >;

  getCurrentOwner: TypedContractMethod<
    [_productId: BytesLike],
    [string],
    "view"
  >;

  getCustodyHistory: TypedContractMethod<
    [_productId: BytesLike],
    [ChainOfCustody.CustodyRecordStructOutput[]],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  initializeCustody: TypedContractMethod<
    [_productId: BytesLike],
    [void],
    "nonpayable"
  >;

  initiateTransfer: TypedContractMethod<
    [_productId: BytesLike, _to: AddressLike],
    [void],
    "nonpayable"
  >;

  pendingTransfer: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  productRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<
    [_productId: BytesLike, _locationGPS: string, _notes: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentOwner"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "custodyChain"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, string] & {
        from: string;
        to: string;
        locationGPS: string;
        timestamp: bigint;
        notes: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentOwner"
  ): TypedContractMethod<[_productId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCustodyHistory"
  ): TypedContractMethod<
    [_productId: BytesLike],
    [ChainOfCustody.CustodyRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initializeCustody"
  ): TypedContractMethod<[_productId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [_productId: BytesLike, _to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingTransfer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "productRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CustodyTransferred"
  ): TypedContractEvent<
    CustodyTransferredEvent.InputTuple,
    CustodyTransferredEvent.OutputTuple,
    CustodyTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "CustodyTransferred(bytes32,address,address)": TypedContractEvent<
      CustodyTransferredEvent.InputTuple,
      CustodyTransferredEvent.OutputTuple,
      CustodyTransferredEvent.OutputObject
    >;
    CustodyTransferred: TypedContractEvent<
      CustodyTransferredEvent.InputTuple,
      CustodyTransferredEvent.OutputTuple,
      CustodyTransferredEvent.OutputObject
    >;

    "TransferInitiated(bytes32,address,address)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
