/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProductRegistry {
  export type ProductStruct = {
    productId: BytesLike;
    farmer: AddressLike;
    productType: string;
    quantity: BigNumberish;
    harvestDate: BigNumberish;
    farmGPS: string;
    metadataHash: BytesLike;
    isActive: boolean;
  };

  export type ProductStructOutput = [
    productId: string,
    farmer: string,
    productType: string,
    quantity: bigint,
    harvestDate: bigint,
    farmGPS: string,
    metadataHash: string,
    isActive: boolean
  ] & {
    productId: string;
    farmer: string;
    productType: string;
    quantity: bigint;
    harvestDate: bigint;
    farmGPS: string;
    metadataHash: string;
    isActive: boolean;
  };
}

export interface ProductRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "farmerProducts"
      | "getFarmerProducts"
      | "getProduct"
      | "identityRegistry"
      | "products"
      | "registerProduct"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProductRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "farmerProducts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFarmerProducts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "products", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [string, BigNumberish, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "farmerProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFarmerProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [
    productId: BytesLike,
    farmer: AddressLike,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    farmer: string,
    quantity: bigint
  ];
  export interface OutputObject {
    productId: string;
    farmer: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProductRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProductRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProductRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  farmerProducts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFarmerProducts: TypedContractMethod<
    [_farmer: AddressLike],
    [string[]],
    "view"
  >;

  getProduct: TypedContractMethod<
    [_productId: BytesLike],
    [ProductRegistry.ProductStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  products: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, string, string, boolean] & {
        productId: string;
        farmer: string;
        productType: string;
        quantity: bigint;
        harvestDate: bigint;
        farmGPS: string;
        metadataHash: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  registerProduct: TypedContractMethod<
    [
      _productType: string,
      _quantity: BigNumberish,
      _harvestDate: BigNumberish,
      _farmGPS: string,
      _metadataHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "farmerProducts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFarmerProducts"
  ): TypedContractMethod<[_farmer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [_productId: BytesLike],
    [ProductRegistry.ProductStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, string, string, boolean] & {
        productId: string;
        farmer: string;
        productType: string;
        quantity: bigint;
        harvestDate: bigint;
        farmGPS: string;
        metadataHash: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<
    [
      _productType: string,
      _quantity: BigNumberish,
      _harvestDate: BigNumberish,
      _farmGPS: string,
      _metadataHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;

  filters: {
    "ProductRegistered(bytes32,address,uint256)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
  };
}
