/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace QualityVerification {
  export type CertificateStruct = {
    productId: BytesLike;
    certificateType: string;
    status: BigNumberish;
    issuedAt: BigNumberish;
    issuedBy: AddressLike;
  };

  export type CertificateStructOutput = [
    productId: string,
    certificateType: string,
    status: bigint,
    issuedAt: bigint,
    issuedBy: string
  ] & {
    productId: string;
    certificateType: string;
    status: bigint;
    issuedAt: bigint;
    issuedBy: string;
  };

  export type QualityReportStruct = {
    productId: BytesLike;
    verifier: AddressLike;
    tier: BigNumberish;
    pesticideLevel: BigNumberish;
    moistureLevel: BigNumberish;
    meetsStandards: boolean;
    timestamp: BigNumberish;
    reportHash: BytesLike;
  };

  export type QualityReportStructOutput = [
    productId: string,
    verifier: string,
    tier: bigint,
    pesticideLevel: bigint,
    moistureLevel: bigint,
    meetsStandards: boolean,
    timestamp: bigint,
    reportHash: string
  ] & {
    productId: string;
    verifier: string;
    tier: bigint;
    pesticideLevel: bigint;
    moistureLevel: bigint;
    meetsStandards: boolean;
    timestamp: bigint;
    reportHash: string;
  };
}

export interface QualityVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_MOISTURE_PERCENT_X100"
      | "MAX_PESTICIDE_PPB"
      | "accreditedLabs"
      | "addAccreditedLab"
      | "certificates"
      | "getCertificate"
      | "getLatestReport"
      | "identityRegistry"
      | "isProductCertified"
      | "productRegistry"
      | "productReports"
      | "revokeCertificate"
      | "submitFarmerClaim"
      | "submitLabReport"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateRevoked"
      | "QualityReportSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_MOISTURE_PERCENT_X100",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PESTICIDE_PPB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accreditedLabs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAccreditedLab",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestReport",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isProductCertified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "productRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productReports",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFarmerClaim",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitLabReport",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_MOISTURE_PERCENT_X100",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PESTICIDE_PPB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accreditedLabs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAccreditedLab",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProductCertified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFarmerClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitLabReport",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [productId: BytesLike, certificateType: string];
  export type OutputTuple = [productId: string, certificateType: string];
  export interface OutputObject {
    productId: string;
    certificateType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [productId: BytesLike, reason: string];
  export type OutputTuple = [productId: string, reason: string];
  export interface OutputObject {
    productId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QualityReportSubmittedEvent {
  export type InputTuple = [
    productId: BytesLike,
    verifier: AddressLike,
    tier: BigNumberish
  ];
  export type OutputTuple = [productId: string, verifier: string, tier: bigint];
  export interface OutputObject {
    productId: string;
    verifier: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QualityVerification extends BaseContract {
  connect(runner?: ContractRunner | null): QualityVerification;
  waitForDeployment(): Promise<this>;

  interface: QualityVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_MOISTURE_PERCENT_X100: TypedContractMethod<[], [bigint], "view">;

  MAX_PESTICIDE_PPB: TypedContractMethod<[], [bigint], "view">;

  accreditedLabs: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  addAccreditedLab: TypedContractMethod<
    [_lab: AddressLike],
    [void],
    "nonpayable"
  >;

  certificates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        productId: string;
        certificateType: string;
        status: bigint;
        issuedAt: bigint;
        issuedBy: string;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [_productId: BytesLike],
    [QualityVerification.CertificateStructOutput],
    "view"
  >;

  getLatestReport: TypedContractMethod<
    [_productId: BytesLike],
    [QualityVerification.QualityReportStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isProductCertified: TypedContractMethod<
    [_productId: BytesLike],
    [boolean],
    "view"
  >;

  productRegistry: TypedContractMethod<[], [string], "view">;

  productReports: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean, bigint, string] & {
        productId: string;
        verifier: string;
        tier: bigint;
        pesticideLevel: bigint;
        moistureLevel: bigint;
        meetsStandards: boolean;
        timestamp: bigint;
        reportHash: string;
      }
    ],
    "view"
  >;

  revokeCertificate: TypedContractMethod<
    [_productId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;

  submitFarmerClaim: TypedContractMethod<
    [
      _productId: BytesLike,
      _pesticideLevel: BigNumberish,
      _moistureLevel: BigNumberish,
      _reportHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitLabReport: TypedContractMethod<
    [
      _productId: BytesLike,
      _pesticideLevel: BigNumberish,
      _moistureLevel: BigNumberish,
      _reportHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_MOISTURE_PERCENT_X100"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PESTICIDE_PPB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accreditedLabs"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "addAccreditedLab"
  ): TypedContractMethod<[_lab: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        productId: string;
        certificateType: string;
        status: bigint;
        issuedAt: bigint;
        issuedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [_productId: BytesLike],
    [QualityVerification.CertificateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestReport"
  ): TypedContractMethod<
    [_productId: BytesLike],
    [QualityVerification.QualityReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isProductCertified"
  ): TypedContractMethod<[_productId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "productRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "productReports"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean, bigint, string] & {
        productId: string;
        verifier: string;
        tier: bigint;
        pesticideLevel: bigint;
        moistureLevel: bigint;
        meetsStandards: boolean;
        timestamp: bigint;
        reportHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<
    [_productId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitFarmerClaim"
  ): TypedContractMethod<
    [
      _productId: BytesLike,
      _pesticideLevel: BigNumberish,
      _moistureLevel: BigNumberish,
      _reportHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitLabReport"
  ): TypedContractMethod<
    [
      _productId: BytesLike,
      _pesticideLevel: BigNumberish,
      _moistureLevel: BigNumberish,
      _reportHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "QualityReportSubmitted"
  ): TypedContractEvent<
    QualityReportSubmittedEvent.InputTuple,
    QualityReportSubmittedEvent.OutputTuple,
    QualityReportSubmittedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(bytes32,string)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(bytes32,string)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "QualityReportSubmitted(bytes32,address,uint8)": TypedContractEvent<
      QualityReportSubmittedEvent.InputTuple,
      QualityReportSubmittedEvent.OutputTuple,
      QualityReportSubmittedEvent.OutputObject
    >;
    QualityReportSubmitted: TypedContractEvent<
      QualityReportSubmittedEvent.InputTuple,
      QualityReportSubmittedEvent.OutputTuple,
      QualityReportSubmittedEvent.OutputObject
    >;
  };
}
